### ISSUE TITLE
Wrong documentation for supported kubernetes Version

### ISSUE THREAD

**Issue by Brice187** [tribe29/checkmk-docs#20]
https://docs.checkmk.com/latest/en/monitoring_kubernetes.html

> Support forKubernetes versions 1.18 and newer is currently limited, due to the fact that the official Kubernetes Python Client is not yet compatible with Kubernetes' newest API versions.

The python client supports Kubernetes ver. 1.21.x
https://github.com/kubernetes-client/python

**Comment by sebkir** [comment]
1. The Kubernetes Python Client 21.0 is only available as an alpha version.
2. It has only been available for 6 days.
3. We will have to check what and how this works now.

**Comment by sebkir** [comment]
The Kubernetes monitoring has been completely re-worked and also the documentation is almost completely new. The issue with the supported versions of Kubernetes is handled in the Helm charts and not part of the documentation anymore.
