### ISSUE TITLE
Mention that plugin must be marked as executable

### ISSUE THREAD

**Issue by itsJohnySmith** [tribe29/checkmk-docs#54]
https://docs.checkmk.com/latest/en/monitoring_docker.html

Add clarification that plugin must me marked as executable, for example:

2. Setting up
2.1. Installing the agent and plug-in
To be able to monitor a Docker node with Checkmk, it must first be monitored with the normal Linux agent. This will give you a basic monitoring of the host system, however there will be no information about the Docker daemon or about the container.

You will need the mk_docker.py agent plug-in, which you can find here: Setup > Agents > Other operating systems > Plugins

Install the plug-in to /usr/lib/check_mk_agent/plugins. For information on installing an agent plug-in, see the Linux agent article.

```
mv mk_docker.py /usr/lib/check_mk_agent/plugins
chmod + x /usr/lib/check_mk_agent/plugins/mk_docker.py
```

**Comment by mschlenker** [comment]
Done in both languages and cherry-picked to 2.1.0 branch. Should become visible online at 22:10 UTC. 

Thanks for helping to improve the Checkmk documentation.
